# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a98e031220f5b0132829f4ae4218fdc7ee5f8c81fb2b0f26b5223f2c9b8c15461a12b474d476735e2f75c8ee872b0b6bc83b2eb10d59eb0f41fad8d1741da6c

test:
  secret_key_base: 1611ed6e63b37d91ca087a29b9da8d696f3a692dc2fc5f7949ca6119d4e4b09c9b1c03c6d374fd3311d7b13ad8b0e59276073fc9544e13d2023c5c76b7c340fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
